# Generated by Django 5.2.5 on 2025-10-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_advisor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaoCaoTaiChinh',
            new_name='TongHopTaiChinh',
        ),
    ]
