# Generated by Django 5.2.5 on 2025-10-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_advisor', '0002_rename_baocaotaichinh_tonghoptaichinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thitruongchungkhoang',
            name='giaCaoNhat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá cao nhất (nghìn VNĐ)'),
        ),
        migrations.AlterField(
            model_name='thitruongchungkhoang',
            name='giaDieuChinh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá điều chỉnh (nghìn VNĐ)'),
        ),
        migrations.AlterField(
            model_name='thitruongchungkhoang',
            name='giaDongCua',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá đóng cửa (nghìn VNĐ)'),
        ),
        migrations.AlterField(
            model_name='thitruongchungkhoang',
            name='giaMoCua',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá mở cửa (nghìn VNĐ)'),
        ),
        migrations.AlterField(
            model_name='thitruongchungkhoang',
            name='giaThapNhat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá thấp nhất (nghìn VNĐ)'),
        ),
        migrations.AlterField(
            model_name='thitruongchungkhoang',
            name='gtKhopLenh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='GT khớp lệnh (tỷ VNĐ)'),
        ),
        migrations.AlterField(
            model_name='thitruongchungkhoang',
            name='klKhopLenh',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='KL khớp lệnh'),
        ),
        migrations.AlterField(
            model_name='thitruongchungkhoang',
            name='thayDoi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Thay đổi giá (+/-)'),
        ),
    ]
