# Generated by Django 5.2.5 on 2025-10-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_advisor', '0003_alter_thitruongchungkhoang_giacaonhat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonghoptaichinh',
            name='quy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quý'),
        ),
    ]
