# Generated by Django 5.2.5 on 2025-11-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_advisor', '0005_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
    ]
