# Generated by Django 5.2.5 on 2025-12-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_advisor', '0006_remove_conversation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tiêu đề bài viết')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung bài viết')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Liên kết bài viết')),
                ('time_post', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đăng bài')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Tóm tắt bài viết')),
            ],
            options={
                'verbose_name': 'Bài Tin Tức',
                'verbose_name_plural': 'Các Bài Tin Tức',
                'constraints': [models.UniqueConstraint(fields=('title', 'time_post'), name='unique_title_time_post')],
            },
        ),
    ]
